Project- Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes

Data Source - by Ybifoundation Gitbut('https://github.com/YBIFoundation/MachineLearning/raw/refs/heads/main/Dataset/Women%20Clothing%20E-Commerce%20Review.csv')

Description- The Multinominal Native Bayes classifier is suitable for classification with discrete features (e.g, words count for text classification).The multinominal distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

Import Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt


In [4]:
import seaborn as sns

Import Dataset

In [5]:
df=pd.read_csv('https://github.com/YBIFoundation/MachineLearning/raw/refs/heads/main/Dataset/Women%20Clothing%20E-Commerce%20Review.csv')

In [6]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [8]:
df.shape

(23486, 10)

Missing Values
remove missing values in reviews column with no review text

In [9]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [10]:
df[df['Review']==""]=np.NaN

In [11]:
df['Review'].fillna("No Review",inplace=True)

<ipython-input-11-bf3889ddac67>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review'].fillna("No Review",inplace=True)


In [12]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [13]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

Define Target Y and Feature X

In [14]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [15]:
X=df['Review']

In [16]:
y=df['Rating']

In [17]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Train Test Split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.1,random_state=2529)

In [20]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((21137,), (2349,), (21137,), (2349,))

Get Feature Text Conversion to Tokens

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [23]:
X_train=cv.fit_transform(X_train)

In [24]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 bought', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [25]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
X_test=cv.fit_transform(X_test)

In [27]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 got', ..., 'years ago', 'yellow orange',
       'yoga pants'], dtype=object)

In [28]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Get Model Train

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
model=MultinomialNB()

In [31]:
model.fit(X_train,y_train)

MultinomialNB()

Get Model Prediction

In [32]:
y_pred=model.predict(X_test)

In [33]:
y_pred.shape

(2349,)

In [34]:
y_pred

array([2, 3, 1, ..., 4, 5, 4])

Get Probability of Each Predicted Class

In [35]:
model.predict_proba(X_test)

array([[0.03928382, 0.88031605, 0.03708557, 0.03745324, 0.00586133],
       [0.10584181, 0.0132302 , 0.37203885, 0.27086689, 0.23802224],
       [0.41472346, 0.24701582, 0.02079816, 0.09073962, 0.22672293],
       ...,
       [0.01235965, 0.00968378, 0.08669104, 0.76876005, 0.12250548],
       [0.01611809, 0.01740038, 0.03168947, 0.08750431, 0.84728775],
       [0.06061429, 0.03590347, 0.03069797, 0.67667181, 0.19611247]])

Get Model Evaluation

In [36]:
from sklearn.metrics import confusion_matrix,classification_report

In [37]:
print(confusion_matrix(y_test,y_pred))

[[  4   8   8  15  51]
 [ 17  10  13  27  77]
 [ 34  16  26  55 140]
 [ 58  51  57  85 267]
 [171 110 119 193 737]]


In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.01      0.05      0.02        86
           2       0.05      0.07      0.06       144
           3       0.12      0.10      0.11       271
           4       0.23      0.16      0.19       518
           5       0.58      0.55      0.57      1330

    accuracy                           0.37      2349
   macro avg       0.20      0.19      0.19      2349
weighted avg       0.40      0.37      0.38      2349



Recategories Rating as Poor (0) and Good(1)

In [39]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Re-rating as 1,2,3 as 0 and 4,5 as 1

In [40]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [41]:
y=df['Rating']

In [42]:
X=df['Review']

Train Test Split

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.1,stratify=y,random_state=2529)

In [45]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((21137,), (2349,), (21137,), (2349,))

Get Feature Text Conversion to Tokens

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.1,stratify=y,random_state=2529)

In [48]:
X_train=cv.fit_transform(X_train)

In [49]:
X_test=cv.fit_transform(X_test)

Get Model Re-Train

In [50]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
model=MultinomialNB()

In [52]:
model.fit(X_train,y_train)

MultinomialNB()

Get Model Prediction

In [53]:
y_pred=model.predict(X_test)

In [54]:
y_pred.shape

(2349,)

In [55]:
y_pred

array([0, 1, 1, ..., 0, 1, 1])

Get Model Evaluation

In [56]:
from sklearn.metrics import confusion_matrix,classification_report

In [57]:
print(confusion_matrix(y_test,y_pred))

[[ 121  407]
 [ 314 1507]]


In [58]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.28      0.23      0.25       528
           1       0.79      0.83      0.81      1821

    accuracy                           0.69      2349
   macro avg       0.53      0.53      0.53      2349
weighted avg       0.67      0.69      0.68      2349

